-- Create the airport_pickup_bookings table
CREATE TABLE airport_pickup_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    service_type TEXT NOT NULL,
    flight_number TEXT,
    arrival_date DATE,
    arrival_time TIME,
    dropoff_location TEXT,
    departure_flight_number TEXT,
    departure_date DATE,
    departure_time TIME,
    pickup_location TEXT,
    passengers INT NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
);

-- Enable Row Level Security
ALTER TABLE airport_pickup_bookings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON airport_pickup_bookings
FOR SELECT USING (true);

-- Create policy to allow public insert access
CREATE POLICY "Allow public insert access" ON airport_pickup_bookings
FOR INSERT WITH CHECK (true); 