-- Create the testimonials table
CREATE TABLE testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT,
    quote TEXT NOT NULL,
    image_url TEXT,
    rating INT CHECK (rating >= 1 AND rating <= 5),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON testimonials
FOR SELECT USING (true);

-- Create indexes for performance
CREATE INDEX idx_testimonials_created_at ON testimonials(created_at); 